
version: '3'
services:
  api:
    container_name: api
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/projeto_aluno
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./:/app
    ports:
      - "8080:8080"      
    networks:
      - postgres-net
    depends_on:
      - db
  
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
     POSTGRES_DB: projeto_aluno
    networks:
      - postgres-net

networks:
  postgres-net:
    driver: bridge